apiVersion: v1
kind: PersistentVolume
metadata:
  name: winov-data
  labels:
    app: winovk8s-app
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: "/nfs/winov-data"