apiVersion: v1
kind: Service
metadata:
  name: winovk8s-service
  labels:
    app: winovk8s-app
spec:
  selector:
    app: winovk8s-app
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: consul
    protocol: TCP
    port: 8500
    targetPort: 8500
